{
  "name": "backrest",
  "parent": "root",
  "variants": [
    {
      "name": "standard_backrest",
      "parameters": {
        "x_length": [0.3, 0.5],
        "y_length": [0.015, 0.1],
        "z_length": [0.3, 0.5]
      },
      "location": {
        "x": 0,
        "y": "parent y_length / 2",
        "z": 0
      },
      "cad_operations": [
        { "name": "sketch_rectangle" },
        { "name": "extrude" },
        {
          "name": "fillet_or_chamfer",
          "probability": 0.8,
          "sub_parameters": {
            "radius": "[0.01, 0.02]",
            "edges": [0, 1]
          }
        },
        {
          "name": "subtract",
          "probability": 0.8,
          "sub_parameters": {
            "shape": ["square", "triangle", "cylinder"],
            "shape_details": {
              "square": {
                "location": { "x": 0, "y": 0, "z": "z_length / 2" },
                "size": [
                  "x_length * [0.2, 0.8]",
                  0,
                  "z_length * [0.2, 0.8]"
                ]
              },
              "triangle": {
                "location": { "x": 0, "y": 0, "z": "z_length / 2" },
                "size": [
                  "x_length * [0.2, 0.8]",
                  0,
                  "z_length * [0.2, 0.8]"
                ]
              },
              "cylinder": {
                "location": { "x": 0, "y": -0.1, "z": "z_length / 2" },
                "radius": "y_length * [0.2, 0.45]",
                "size": ["radius", 0, "radius"]
              }
            }
          }
        }
      ]
    }
  ]
}
