{
  "name": "leg_body",
  "children" : [],
  "parent": "leg",
  "variants": [



   {
      "name": "cylindrical_leg",
        "boolean" : "addition",
      "parameters": {
        "x_length": [0.01, 0.05],
        "y_length": [0.01, 0.05],
        "z_length": [0.3, 0.6]
      },
      "quantity": 4,
      "locations": [
        {
          "x_location": "-parent x_length / 2 + x_length / 2",
          "y_location": "-parent y_length / 2 + y_length / 2",
          "z_location": "-z_length"
        },
        {
          "x_location": "parent x_length / 2 - x_length / 2",
          "y_location": "-parent y_length / 2 + y_length / 2",
          "z_location": "-z_length"
        },
        {
          "x_location": "-parent x_length / 2 + x_length / 2",
          "y_location": "parent y_length / 2 - y_length / 2",
          "z_location": "-z_length"
        },
        {
          "x_location": "parent x_length / 2 - x_length / 2",
          "y_location": "parent y_length / 2 - y_length / 2",
          "z_location": "-z_length"
        }
      ],
      "cad_operations": [
        { "name": "sketch_circle" },
        { "name": "extrude" }
      ]
    }




  ]
}
